#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_SOS) += sos

sos-components-$(CONFIG_APP_SOSH) += sosh
sos-components-$(CONFIG_APP_TTY_TEST) += tty_test
sos-components=$(addprefix $(STAGE_BASE)/bin/, $(sos-components-y))
sos-components-$(CONFIG_APP_GAME) += game
sos-components-$(CONFIG_APP_THRASH) += thrash

# Test programs
sos-components-$(CONFIG_APP_ERROR_TEST) += error_test
sos-components-$(CONFIG_APP_EXEC_STACK) += execstack
sos-components-$(CONFIG_APP_PAGINGDEMO) += pagingdemo

sos: export COMPONENTS=${sos-components}
sos: ${sos-components-y} \
     libsel4 libelf $(libc) libcpio \
     libsel4cspace libserial libclock \
     liblwip libnfs libethdrivers \
     libsos libplatsupport libutils
